-- MySQL Script generated by MySQL Workbench
-- Tue Mar 17 10:48:58 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` CHAR(11) NOT NULL,
  PRIMARY KEY (`id_aluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`curso` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `nível` ENUM('A1', 'A2', 'B1', 'B2', 'C1', 'C2') NOT NULL,
  `idioma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turma` (
  `id_turma` INT NOT NULL AUTO_INCREMENT,
  `turno` ENUM('M', 'T') NOT NULL DEFAULT 'M',
  `id_curso` INT NOT NULL,
  PRIMARY KEY (`id_turma`),
  INDEX `id_curso_idx` (`id_curso` ASC) VISIBLE,
  CONSTRAINT `id_curso`
    FOREIGN KEY (`id_curso`)
    REFERENCES `mydb`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`matrícula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`matrícula` (
  `id_matrícula` CHAR(8) NOT NULL,
  `data_matricula` DATE NOT NULL,
  `id_aluno` INT NOT NULL,
  `id_turma` INT NOT NULL,
  PRIMARY KEY (`id_matrícula`),
  INDEX `id_aluno_idx` (`id_aluno` ASC) VISIBLE,
  INDEX `id_turma_idx` (`id_turma` ASC) VISIBLE,
  CONSTRAINT `id_aluno`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `mydb`.`aluno` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_turma`
    FOREIGN KEY (`id_turma`)
    REFERENCES `mydb`.`turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professor` (
  `id_professor` INT NOT NULL AUTO_INCREMENT,
  `idioma` VARCHAR(15) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_professor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turma_professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turma_professor` (
  `id_turma` INT NOT NULL,
  `id_professor` INT NOT NULL,
  INDEX `id_turma_idx` (`id_turma` ASC) VISIBLE,
  INDEX `id_professor_idx` (`id_professor` ASC) VISIBLE,
  CONSTRAINT `id_turma`
    FOREIGN KEY (`id_turma`)
    REFERENCES `mydb`.`turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_professor`
    FOREIGN KEY (`id_professor`)
    REFERENCES `mydb`.`professor` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
